services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      - ./env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/mariadb # /home/anamieta/data/mariadb
      o: bind
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: ./data/wordpress # /home/anamieta/data/wordpress
      o: bind

