version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
      - .env:/var/www/html/srcs/.env
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_files:
    driver: local

