services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/anamieta/data/mariadb
      o: bind
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/anamieta/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
